/*
Navicat MySQL Data Transfer

Source Server         : zk
Source Server Version : 50717
Source Host           : localhost:3306
Source Database       : android_api

Target Server Type    : MYSQL
Target Server Version : 50717
File Encoding         : 65001

Date: 2017-05-04 13:42:18
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `package_list`
-- ----------------------------
DROP TABLE IF EXISTS `package_list`;
CREATE TABLE `package_list` (
  `package_name` varchar(255) NOT NULL,
  `package_url` varchar(255) DEFAULT NULL,
  `api_level` varchar(255) DEFAULT NULL,
  `package_des` varchar(1024) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=289 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of package_list
-- ----------------------------
INSERT INTO `package_list` VALUES ('android', 'https://developer.android.com/reference/android/package-summary.html', '1', 'Contains resource classes used by applications included in the platform and defines application\npermissions for system features.', '1');
INSERT INTO `package_list` VALUES ('android.accessibilityservice', 'https://developer.android.com/reference/android/accessibilityservice/package-summary.html', '4', '\n  The classes in this package are used for development of accessibility service that\n  provide alternative or augmented feedback to the user.', '2');
INSERT INTO `package_list` VALUES ('android.accounts', 'https://developer.android.com/reference/android/accounts/package-summary.html', '5', '', '3');
INSERT INTO `package_list` VALUES ('android.animation', 'https://developer.android.com/reference/android/animation/package-summary.html', '11', '\nThese classes provide functionality for the property animation system, which allows you \nto animate object properties of any type. ', '4');
INSERT INTO `package_list` VALUES ('android.annotation', 'https://developer.android.com/reference/android/annotation/package-summary.html', '16', '', '5');
INSERT INTO `package_list` VALUES ('android.app', 'https://developer.android.com/reference/android/app/package-summary.html', '1', 'Contains high-level classes encapsulating the overall Android application model.', '6');
INSERT INTO `package_list` VALUES ('android.app.admin', 'https://developer.android.com/reference/android/app/admin/package-summary.html', '8', 'Provides device administration features at the system level, allowing you to create\nsecurity-aware applications that are useful in enterprise settings, in which IT professionals\nrequire rich control over employee devices.', '7');
INSERT INTO `package_list` VALUES ('android.app.assist', 'https://developer.android.com/reference/android/app/assist/package-summary.html', '23', '', '8');
INSERT INTO `package_list` VALUES ('android.app.backup', 'https://developer.android.com/reference/android/app/backup/package-summary.html', '8', 'Contains the backup and restore functionality available to\napplications. If a user wipes the data on their device or upgrades to a new Android-powered\ndevice, all applications that have enabled backup can restore the user\'s previous data when the\napplication is reinstalled.', '9');
INSERT INTO `package_list` VALUES ('android.app.job', 'https://developer.android.com/reference/android/app/job/package-summary.html', '21', '', '10');
INSERT INTO `package_list` VALUES ('android.app.usage', 'https://developer.android.com/reference/android/app/usage/package-summary.html', '21', '', '11');
INSERT INTO `package_list` VALUES ('android.appwidget', 'https://developer.android.com/reference/android/appwidget/package-summary.html', '3', 'Contains the components necessary to create \"app widgets\", which users can embed in other\napplications (such as the home screen) to quickly access application data and services without\nlaunching a new activity.', '12');
INSERT INTO `package_list` VALUES ('android.bluetooth', 'https://developer.android.com/reference/android/bluetooth/package-summary.html', '5', 'Provides classes that manage Bluetooth functionality, such as scanning for\ndevices, connecting with devices, and managing data transfer between devices.\nThe Bluetooth API supports both \"Classic Bluetooth\" and Bluetooth Low Energy.', '13');
INSERT INTO `package_list` VALUES ('android.bluetooth.le', 'https://developer.android.com/reference/android/bluetooth/le/package-summary.html', '21', '', '14');
INSERT INTO `package_list` VALUES ('android.companion', 'https://developer.android.com/reference/android/companion/package-summary.html', 'O', '', '15');
INSERT INTO `package_list` VALUES ('android.content', 'https://developer.android.com/reference/android/content/package-summary.html', '1', 'Contains classes for accessing and publishing data on a device.', '16');
INSERT INTO `package_list` VALUES ('android.content.pm', 'https://developer.android.com/reference/android/content/pm/package-summary.html', '1', 'Contains classes for accessing information about an\napplication package, including information about its activities,\npermissions, services, signatures, and providers.', '17');
INSERT INTO `package_list` VALUES ('android.content.res', 'https://developer.android.com/reference/android/content/res/package-summary.html', '1', 'Contains classes for accessing application resources,\nsuch as raw asset files, colors, drawables, media or other other files\nin the package, plus important device configuration details\n(orientation, input types, etc.) that affect how the application may behave.', '18');
INSERT INTO `package_list` VALUES ('android.database', 'https://developer.android.com/reference/android/database/package-summary.html', '1', 'Contains classes to explore data returned through a content provider.', '19');
INSERT INTO `package_list` VALUES ('android.database.sqlite', 'https://developer.android.com/reference/android/database/sqlite/package-summary.html', '1', 'Contains the SQLite database management\nclasses that an application would use to manage its own private database.', '20');
INSERT INTO `package_list` VALUES ('android.databinding', 'https://developer.android.com/reference/android/databinding/package-summary.html', '', 'Contains components used when developing applications with data binding.', '21');
INSERT INTO `package_list` VALUES ('android.drm', 'https://developer.android.com/reference/android/drm/package-summary.html', '11', 'Provides classes for managing DRM content and determining the capabilities of DRM plugins\n(agents).', '22');
INSERT INTO `package_list` VALUES ('android.gesture', 'https://developer.android.com/reference/android/gesture/package-summary.html', '4', 'Provides classes to create, recognize, load and save gestures.', '23');
INSERT INTO `package_list` VALUES ('android.graphics', 'https://developer.android.com/reference/android/graphics/package-summary.html', '1', 'Provides low level graphics tools such as canvases, color filters, points, and \nrectangles that let you handle drawing to the screen directly.', '24');
INSERT INTO `package_list` VALUES ('android.graphics.drawable', 'https://developer.android.com/reference/android/graphics/drawable/package-summary.html', '1', 'Provides classes to manage a variety of visual elements that are intended for\ndisplay only, such as bitmaps and gradients.', '25');
INSERT INTO `package_list` VALUES ('android.graphics.drawable.shapes', 'https://developer.android.com/reference/android/graphics/drawable/shapes/package-summary.html', '1', 'Contains classes for drawing geometric shapes.', '26');
INSERT INTO `package_list` VALUES ('android.graphics.fonts', 'https://developer.android.com/reference/android/graphics/fonts/package-summary.html', 'O', '', '27');
INSERT INTO `package_list` VALUES ('android.graphics.pdf', 'https://developer.android.com/reference/android/graphics/pdf/package-summary.html', '19', 'Contains classes for manipulation of PDF content.', '28');
INSERT INTO `package_list` VALUES ('android.hardware', 'https://developer.android.com/reference/android/hardware/package-summary.html', '1', 'Provides support for hardware features, such as the camera and other sensors.', '29');
INSERT INTO `package_list` VALUES ('android.hardware.camera2', 'https://developer.android.com/reference/android/hardware/camera2/package-summary.html', '21', 'The android.hardware.camera2 package provides an interface to\nindividual camera devices connected to an Android device.', '30');
INSERT INTO `package_list` VALUES ('android.hardware.camera2.params', 'https://developer.android.com/reference/android/hardware/camera2/params/package-summary.html', '21', '', '31');
INSERT INTO `package_list` VALUES ('android.hardware.display', 'https://developer.android.com/reference/android/hardware/display/package-summary.html', '17', '', '32');
INSERT INTO `package_list` VALUES ('android.hardware.fingerprint', 'https://developer.android.com/reference/android/hardware/fingerprint/package-summary.html', '23', '', '33');
INSERT INTO `package_list` VALUES ('android.hardware.input', 'https://developer.android.com/reference/android/hardware/input/package-summary.html', '16', '', '34');
INSERT INTO `package_list` VALUES ('android.hardware.usb', 'https://developer.android.com/reference/android/hardware/usb/package-summary.html', '12', 'Provides support to communicate with USB hardware peripherals that are connected to \nAndroid-powered devices.', '35');
INSERT INTO `package_list` VALUES ('android.icu.lang', 'https://developer.android.com/reference/android/icu/lang/package-summary.html', '24', '', '36');
INSERT INTO `package_list` VALUES ('android.icu.math', 'https://developer.android.com/reference/android/icu/math/package-summary.html', '24', '', '37');
INSERT INTO `package_list` VALUES ('android.icu.text', 'https://developer.android.com/reference/android/icu/text/package-summary.html', '24', '', '38');
INSERT INTO `package_list` VALUES ('android.icu.util', 'https://developer.android.com/reference/android/icu/util/package-summary.html', '24', '', '39');
INSERT INTO `package_list` VALUES ('android.inputmethodservice', 'https://developer.android.com/reference/android/inputmethodservice/package-summary.html', '3', 'Base classes for writing input methods (such as software keyboards).', '40');
INSERT INTO `package_list` VALUES ('android.location', 'https://developer.android.com/reference/android/location/package-summary.html', '1', 'Contains the framework API classes that define Android location-based and\n	related services.', '41');
INSERT INTO `package_list` VALUES ('android.media', 'https://developer.android.com/reference/android/media/package-summary.html', '1', 'Provides classes that manage various media interfaces in audio and video.', '42');
INSERT INTO `package_list` VALUES ('android.media.audiofx', 'https://developer.android.com/reference/android/media/audiofx/package-summary.html', '9', 'Provides classes that manage audio effects implemented in the media framework.', '43');
INSERT INTO `package_list` VALUES ('android.media.browse', 'https://developer.android.com/reference/android/media/browse/package-summary.html', '21', '', '44');
INSERT INTO `package_list` VALUES ('android.media.effect', 'https://developer.android.com/reference/android/media/effect/package-summary.html', '14', 'Provides classes that allow you to apply a variety of visual effects to images and\nvideos.', '45');
INSERT INTO `package_list` VALUES ('android.media.midi', 'https://developer.android.com/reference/android/media/midi/package-summary.html', '23', '\nProvides classes for sending and receiving messages using the standard MIDI\nevent protocol over USB, Bluetooth LE, and virtual (inter-app) transports.', '46');
INSERT INTO `package_list` VALUES ('android.media.projection', 'https://developer.android.com/reference/android/media/projection/package-summary.html', '21', '', '47');
INSERT INTO `package_list` VALUES ('android.media.session', 'https://developer.android.com/reference/android/media/session/package-summary.html', '21', '', '48');
INSERT INTO `package_list` VALUES ('android.media.tv', 'https://developer.android.com/reference/android/media/tv/package-summary.html', '21', '', '49');
INSERT INTO `package_list` VALUES ('android.mtp', 'https://developer.android.com/reference/android/mtp/package-summary.html', '12', 'Provides APIs that let you interact directly with connected cameras and other devices, using the\nPTP (Picture Transfer Protocol) subset of the MTP (Media Transfer Protocol) specification.', '50');
INSERT INTO `package_list` VALUES ('android.net', 'https://developer.android.com/reference/android/net/package-summary.html', '1', 'Classes that help with network access, beyond the normal java.net.* APIs.', '51');
INSERT INTO `package_list` VALUES ('android.net.http', 'https://developer.android.com/reference/android/net/http/package-summary.html', '1', '\n', '52');
INSERT INTO `package_list` VALUES ('android.net.nsd', 'https://developer.android.com/reference/android/net/nsd/package-summary.html', '16', '', '53');
INSERT INTO `package_list` VALUES ('android.net.rtp', 'https://developer.android.com/reference/android/net/rtp/package-summary.html', '12', 'Provides APIs for RTP (Real-time Transport Protocol), allowing applications to manage on-demand\nor interactive data streaming.', '54');
INSERT INTO `package_list` VALUES ('android.net.sip', 'https://developer.android.com/reference/android/net/sip/package-summary.html', '9', 'Provides access to Session Initiation Protocol (SIP) functionality, such as\nmaking and answering VOIP calls using SIP.', '55');
INSERT INTO `package_list` VALUES ('android.net.wifi', 'https://developer.android.com/reference/android/net/wifi/package-summary.html', '1', 'Provides classes to manage Wi-Fi functionality on the device.', '56');
INSERT INTO `package_list` VALUES ('android.net.wifi.aware', 'https://developer.android.com/reference/android/net/wifi/aware/package-summary.html', 'O', 'Provides classes which allow applications to use Wi-Fi Aware to discover peers and create\n    connections to them.', '57');
INSERT INTO `package_list` VALUES ('android.net.wifi.hotspot2', 'https://developer.android.com/reference/android/net/wifi/hotspot2/package-summary.html', 'O', '', '58');
INSERT INTO `package_list` VALUES ('android.net.wifi.hotspot2.omadm', 'https://developer.android.com/reference/android/net/wifi/hotspot2/omadm/package-summary.html', 'O', '', '59');
INSERT INTO `package_list` VALUES ('android.net.wifi.hotspot2.pps', 'https://developer.android.com/reference/android/net/wifi/hotspot2/pps/package-summary.html', 'O', '', '60');
INSERT INTO `package_list` VALUES ('android.net.wifi.p2p', 'https://developer.android.com/reference/android/net/wifi/p2p/package-summary.html', '14', 'Provides classes to create peer-to-peer (P2P) connections with Wi-Fi Direct.', '61');
INSERT INTO `package_list` VALUES ('android.net.wifi.p2p.nsd', 'https://developer.android.com/reference/android/net/wifi/p2p/nsd/package-summary.html', '16', '', '62');
INSERT INTO `package_list` VALUES ('android.nfc', 'https://developer.android.com/reference/android/nfc/package-summary.html', '9', 'Provides access to Near Field Communication (NFC) functionality, allowing applications to read\nNDEF message in NFC tags. A \"tag\" may actually be another device that appears as a tag.', '63');
INSERT INTO `package_list` VALUES ('android.nfc.cardemulation', 'https://developer.android.com/reference/android/nfc/cardemulation/package-summary.html', '19', '', '64');
INSERT INTO `package_list` VALUES ('android.nfc.tech', 'https://developer.android.com/reference/android/nfc/tech/package-summary.html', '10', '\nThese classes provide access to a tag technology\'s features, which vary by the type\nof tag that is scanned.', '65');
INSERT INTO `package_list` VALUES ('android.opengl', 'https://developer.android.com/reference/android/opengl/package-summary.html', '1', 'Provides an OpenGL ES static interface and utilities.', '66');
INSERT INTO `package_list` VALUES ('android.os', 'https://developer.android.com/reference/android/os/package-summary.html', '1', 'Provides basic operating system services, message passing, and inter-process\ncommunication on the device.', '67');
INSERT INTO `package_list` VALUES ('android.os.health', 'https://developer.android.com/reference/android/os/health/package-summary.html', '24', 'The android.os.health package contains a set of classes to provide data\nto track the system resources of applications.', '68');
INSERT INTO `package_list` VALUES ('android.os.storage', 'https://developer.android.com/reference/android/os/storage/package-summary.html', '9', '\nContains classes for the system storage service, which manages binary asset filesystems\nknown as Opaque Binary Blobs (OBBs).', '69');
INSERT INTO `package_list` VALUES ('android.preference', 'https://developer.android.com/reference/android/preference/package-summary.html', '1', 'Provides classes that manage application preferences and implement the preferences UI.', '70');
INSERT INTO `package_list` VALUES ('android.print', 'https://developer.android.com/reference/android/print/package-summary.html', '19', '\nProvides classes for implementing print support in applications and also contains all\nbase classes and abstractions involved in printing.', '71');
INSERT INTO `package_list` VALUES ('android.print.pdf', 'https://developer.android.com/reference/android/print/pdf/package-summary.html', '19', '', '72');
INSERT INTO `package_list` VALUES ('android.printservice', 'https://developer.android.com/reference/android/printservice/package-summary.html', '19', '\nProvides classes for implementing print services.', '73');
INSERT INTO `package_list` VALUES ('android.provider', 'https://developer.android.com/reference/android/provider/package-summary.html', '1', 'Provides convenience classes to access the content providers supplied by\nAndroid.', '74');
INSERT INTO `package_list` VALUES ('android.renderscript', 'https://developer.android.com/reference/android/renderscript/package-summary.html', '11', 'RenderScript provides support for high-performance computation across heterogeneous processors.', '75');
INSERT INTO `package_list` VALUES ('android.sax', 'https://developer.android.com/reference/android/sax/package-summary.html', '1', 'A framework that makes it easy to write efficient and robust SAX handlers.', '76');
INSERT INTO `package_list` VALUES ('android.security', 'https://developer.android.com/reference/android/security/package-summary.html', '14', 'Provides access to a few facilities of the Android security\n    subsystems.', '77');
INSERT INTO `package_list` VALUES ('android.security.keystore', 'https://developer.android.com/reference/android/security/keystore/package-summary.html', '23', '', '78');
INSERT INTO `package_list` VALUES ('android.service.autofill', 'https://developer.android.com/reference/android/service/autofill/package-summary.html', 'O', '', '79');
INSERT INTO `package_list` VALUES ('android.service.carrier', 'https://developer.android.com/reference/android/service/carrier/package-summary.html', '22', '', '80');
INSERT INTO `package_list` VALUES ('android.service.chooser', 'https://developer.android.com/reference/android/service/chooser/package-summary.html', '23', '', '81');
INSERT INTO `package_list` VALUES ('android.service.dreams', 'https://developer.android.com/reference/android/service/dreams/package-summary.html', '17', '', '82');
INSERT INTO `package_list` VALUES ('android.service.media', 'https://developer.android.com/reference/android/service/media/package-summary.html', '21', '', '83');
INSERT INTO `package_list` VALUES ('android.service.notification', 'https://developer.android.com/reference/android/service/notification/package-summary.html', '18', '', '84');
INSERT INTO `package_list` VALUES ('android.service.quicksettings', 'https://developer.android.com/reference/android/service/quicksettings/package-summary.html', '24', '', '85');
INSERT INTO `package_list` VALUES ('android.service.restrictions', 'https://developer.android.com/reference/android/service/restrictions/package-summary.html', '21', '', '86');
INSERT INTO `package_list` VALUES ('android.service.textservice', 'https://developer.android.com/reference/android/service/textservice/package-summary.html', '14', 'Provides classes that allow you to create spell checkers in a manner similar to the\ninput method framework (for IMEs).', '87');
INSERT INTO `package_list` VALUES ('android.service.voice', 'https://developer.android.com/reference/android/service/voice/package-summary.html', '21', '', '88');
INSERT INTO `package_list` VALUES ('android.service.vr', 'https://developer.android.com/reference/android/service/vr/package-summary.html', '24', '', '89');
INSERT INTO `package_list` VALUES ('android.service.wallpaper', 'https://developer.android.com/reference/android/service/wallpaper/package-summary.html', '7', '', '90');
INSERT INTO `package_list` VALUES ('android.speech', 'https://developer.android.com/reference/android/speech/package-summary.html', '3', '', '91');
INSERT INTO `package_list` VALUES ('android.speech.tts', 'https://developer.android.com/reference/android/speech/tts/package-summary.html', '4', '', '92');
INSERT INTO `package_list` VALUES ('android.support.animation', 'https://developer.android.com/reference/android/support/animation/package-summary.html', '25.3.0', '', '93');
INSERT INTO `package_list` VALUES ('android.support.annotation', 'https://developer.android.com/reference/android/support/annotation/package-summary.html', '', '', '94');
INSERT INTO `package_list` VALUES ('android.support.app.recommendation', 'https://developer.android.com/reference/android/support/app/recommendation/package-summary.html', '23.0.0', '', '95');
INSERT INTO `package_list` VALUES ('android.support.compat', 'https://developer.android.com/reference/android/support/compat/package-summary.html', '', '', '96');
INSERT INTO `package_list` VALUES ('android.support.coreui', 'https://developer.android.com/reference/android/support/coreui/package-summary.html', '', '', '97');
INSERT INTO `package_list` VALUES ('android.support.coreutils', 'https://developer.android.com/reference/android/support/coreutils/package-summary.html', '', '', '98');
INSERT INTO `package_list` VALUES ('android.support.customtabs', 'https://developer.android.com/reference/android/support/customtabs/package-summary.html', '23.0.0', '', '99');
INSERT INTO `package_list` VALUES ('android.support.design', 'https://developer.android.com/reference/android/support/design/package-summary.html', '', '', '100');
INSERT INTO `package_list` VALUES ('android.support.design.widget', 'https://developer.android.com/reference/android/support/design/widget/package-summary.html', '22.2.0', '', '101');
INSERT INTO `package_list` VALUES ('android.support.dynamicanimation', 'https://developer.android.com/reference/android/support/dynamicanimation/package-summary.html', '', '', '102');
INSERT INTO `package_list` VALUES ('android.support.exifinterface', 'https://developer.android.com/reference/android/support/exifinterface/package-summary.html', '', '', '103');
INSERT INTO `package_list` VALUES ('android.support.fragment', 'https://developer.android.com/reference/android/support/fragment/package-summary.html', '', '', '104');
INSERT INTO `package_list` VALUES ('android.support.graphics.drawable', 'https://developer.android.com/reference/android/support/graphics/drawable/package-summary.html', '23.2.0', '', '105');
INSERT INTO `package_list` VALUES ('android.support.graphics.drawable.animated', 'https://developer.android.com/reference/android/support/graphics/drawable/animated/package-summary.html', '', '', '106');
INSERT INTO `package_list` VALUES ('android.support.media', 'https://developer.android.com/reference/android/support/media/package-summary.html', '25.1.0', '', '107');
INSERT INTO `package_list` VALUES ('android.support.media.instantvideo', 'https://developer.android.com/reference/android/support/media/instantvideo/package-summary.html', '', '', '108');
INSERT INTO `package_list` VALUES ('android.support.media.instantvideo.preload', 'https://developer.android.com/reference/android/support/media/instantvideo/preload/package-summary.html', '26.0.0-alpha1', '', '109');
INSERT INTO `package_list` VALUES ('android.support.media.instantvideo.widget', 'https://developer.android.com/reference/android/support/media/instantvideo/widget/package-summary.html', '26.0.0-alpha1', '', '110');
INSERT INTO `package_list` VALUES ('android.support.media.tv', 'https://developer.android.com/reference/android/support/media/tv/package-summary.html', '26.0.0-alpha1', '', '111');
INSERT INTO `package_list` VALUES ('android.support.mediacompat', 'https://developer.android.com/reference/android/support/mediacompat/package-summary.html', '', '', '112');
INSERT INTO `package_list` VALUES ('android.support.multidex', 'https://developer.android.com/reference/android/support/multidex/package-summary.html', '', '', '113');
INSERT INTO `package_list` VALUES ('android.support.percent', 'https://developer.android.com/reference/android/support/percent/package-summary.html', '23.0.0', '', '114');
INSERT INTO `package_list` VALUES ('android.support.recommendation', 'https://developer.android.com/reference/android/support/recommendation/package-summary.html', '', '', '115');
INSERT INTO `package_list` VALUES ('android.support.transition', 'https://developer.android.com/reference/android/support/transition/package-summary.html', '24.2.0', 'Support android.transition classes to provide transition API back to android API level 14.', '116');
INSERT INTO `package_list` VALUES ('android.support.v13', 'https://developer.android.com/reference/android/support/v13/package-summary.html', '', '', '117');
INSERT INTO `package_list` VALUES ('android.support.v13.app', 'https://developer.android.com/reference/android/support/v13/app/package-summary.html', '22.0.0', 'Support classes to access some of the android.app package features introduced after API level 13 in a backwards compatible fashion.', '118');
INSERT INTO `package_list` VALUES ('android.support.v13.view', 'https://developer.android.com/reference/android/support/v13/view/package-summary.html', '24.0.0', '', '119');
INSERT INTO `package_list` VALUES ('android.support.v13.view.inputmethod', 'https://developer.android.com/reference/android/support/v13/view/inputmethod/package-summary.html', '25.0.0', '', '120');
INSERT INTO `package_list` VALUES ('android.support.v14.preference', 'https://developer.android.com/reference/android/support/v14/preference/package-summary.html', '23.0.0', '', '121');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback', 'https://developer.android.com/reference/android/support/v17/leanback/package-summary.html', '', 'Support classes for building Leanback user experiences.', '122');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback.app', 'https://developer.android.com/reference/android/support/v17/leanback/app/package-summary.html', '22.0.0', 'Support classes providing high level Leanback user interface building blocks:\n fragments and helpers.', '123');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback.database', 'https://developer.android.com/reference/android/support/v17/leanback/database/package-summary.html', '22.0.0', '', '124');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback.graphics', 'https://developer.android.com/reference/android/support/v17/leanback/graphics/package-summary.html', '22.0.0', '', '125');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback.media', 'https://developer.android.com/reference/android/support/v17/leanback/media/package-summary.html', '25.1.0', '', '126');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback.system', 'https://developer.android.com/reference/android/support/v17/leanback/system/package-summary.html', '22.2.1', '', '127');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback.widget', 'https://developer.android.com/reference/android/support/v17/leanback/widget/package-summary.html', '22.0.0', 'Support classes providing low level Leanback user interface building blocks:\n widgets and helpers.', '128');
INSERT INTO `package_list` VALUES ('android.support.v17.leanback.widget.picker', 'https://developer.android.com/reference/android/support/v17/leanback/widget/picker/package-summary.html', '23.2.0', '', '129');
INSERT INTO `package_list` VALUES ('android.support.v17.preference', 'https://developer.android.com/reference/android/support/v17/preference/package-summary.html', '23.0.0', '', '130');
INSERT INTO `package_list` VALUES ('android.support.v4', 'https://developer.android.com/reference/android/support/v4/package-summary.html', '', '', '131');
INSERT INTO `package_list` VALUES ('android.support.v4.accessibilityservice', 'https://developer.android.com/reference/android/support/v4/accessibilityservice/package-summary.html', '22.0.0', 'Support android.accessibilityservice classes to assist with development of applications for\nandroid API level 4 or later.', '132');
INSERT INTO `package_list` VALUES ('android.support.v4.app', 'https://developer.android.com/reference/android/support/v4/app/package-summary.html', '22.0.0', '', '133');
INSERT INTO `package_list` VALUES ('android.support.v4.content', 'https://developer.android.com/reference/android/support/v4/content/package-summary.html', '22.0.0', 'Support android.content classes to assist with development of applications for\nandroid API level 4 or later.', '134');
INSERT INTO `package_list` VALUES ('android.support.v4.content.pm', 'https://developer.android.com/reference/android/support/v4/content/pm/package-summary.html', '22.2.0', 'Support android.content.pm classes to assist with development of applications for\nandroid API level 4 or later.', '135');
INSERT INTO `package_list` VALUES ('android.support.v4.content.res', 'https://developer.android.com/reference/android/support/v4/content/res/package-summary.html', '22.2.0', '', '136');
INSERT INTO `package_list` VALUES ('android.support.v4.database', 'https://developer.android.com/reference/android/support/v4/database/package-summary.html', '22.0.0', 'Support android.database classes to assist with development of applications for\nandroid API level 4 or later.', '137');
INSERT INTO `package_list` VALUES ('android.support.v4.graphics', 'https://developer.android.com/reference/android/support/v4/graphics/package-summary.html', '22.0.0', '', '138');
INSERT INTO `package_list` VALUES ('android.support.v4.graphics.drawable', 'https://developer.android.com/reference/android/support/v4/graphics/drawable/package-summary.html', '22.0.0', '', '139');
INSERT INTO `package_list` VALUES ('android.support.v4.hardware.display', 'https://developer.android.com/reference/android/support/v4/hardware/display/package-summary.html', '22.0.0', '', '140');
INSERT INTO `package_list` VALUES ('android.support.v4.hardware.fingerprint', 'https://developer.android.com/reference/android/support/v4/hardware/fingerprint/package-summary.html', '23.0.0', '', '141');
INSERT INTO `package_list` VALUES ('android.support.v4.math', 'https://developer.android.com/reference/android/support/v4/math/package-summary.html', '26.0.0-alpha1', '', '142');
INSERT INTO `package_list` VALUES ('android.support.v4.media', 'https://developer.android.com/reference/android/support/v4/media/package-summary.html', '22.0.0', '', '143');
INSERT INTO `package_list` VALUES ('android.support.v4.media.session', 'https://developer.android.com/reference/android/support/v4/media/session/package-summary.html', '22.0.0', '', '144');
INSERT INTO `package_list` VALUES ('android.support.v4.net', 'https://developer.android.com/reference/android/support/v4/net/package-summary.html', '22.0.0', '', '145');
INSERT INTO `package_list` VALUES ('android.support.v4.os', 'https://developer.android.com/reference/android/support/v4/os/package-summary.html', '22.0.0', 'Support android.os classes to assist with development of applications for\nandroid API level 4 or later.', '146');
INSERT INTO `package_list` VALUES ('android.support.v4.print', 'https://developer.android.com/reference/android/support/v4/print/package-summary.html', '22.0.0', '', '147');
INSERT INTO `package_list` VALUES ('android.support.v4.provider', 'https://developer.android.com/reference/android/support/v4/provider/package-summary.html', '22.0.0', '', '148');
INSERT INTO `package_list` VALUES ('android.support.v4.text', 'https://developer.android.com/reference/android/support/v4/text/package-summary.html', '22.0.0', '', '149');
INSERT INTO `package_list` VALUES ('android.support.v4.text.util', 'https://developer.android.com/reference/android/support/v4/text/util/package-summary.html', '24.2.0', '', '150');
INSERT INTO `package_list` VALUES ('android.support.v4.util', 'https://developer.android.com/reference/android/support/v4/util/package-summary.html', '22.0.0', 'Support android.util classes to assist with development of applications for\nandroid API level 4 or later.', '151');
INSERT INTO `package_list` VALUES ('android.support.v4.view', 'https://developer.android.com/reference/android/support/v4/view/package-summary.html', '22.0.0', 'Support android.util classes to assist with development of applications for\nandroid API level 4 or later.', '152');
INSERT INTO `package_list` VALUES ('android.support.v4.view.accessibility', 'https://developer.android.com/reference/android/support/v4/view/accessibility/package-summary.html', '22.0.0', 'Support classes to access some of the android.view.accessibility package features introduced after API level 4 in a backwards compatible fashion.', '153');
INSERT INTO `package_list` VALUES ('android.support.v4.view.animation', 'https://developer.android.com/reference/android/support/v4/view/animation/package-summary.html', '22.1.0', '', '154');
INSERT INTO `package_list` VALUES ('android.support.v4.widget', 'https://developer.android.com/reference/android/support/v4/widget/package-summary.html', '22.0.0', 'Support android.widget classes to assist with development of applications for\nandroid API level 4 or later.', '155');
INSERT INTO `package_list` VALUES ('android.support.v7.app', 'https://developer.android.com/reference/android/support/v7/app/package-summary.html', '22.0.0', '', '156');
INSERT INTO `package_list` VALUES ('android.support.v7.appcompat', 'https://developer.android.com/reference/android/support/v7/appcompat/package-summary.html', '22.2.0', '', '157');
INSERT INTO `package_list` VALUES ('android.support.v7.cardview', 'https://developer.android.com/reference/android/support/v7/cardview/package-summary.html', '', '', '158');
INSERT INTO `package_list` VALUES ('android.support.v7.content.res', 'https://developer.android.com/reference/android/support/v7/content/res/package-summary.html', '24.0.0', '', '159');
INSERT INTO `package_list` VALUES ('android.support.v7.graphics', 'https://developer.android.com/reference/android/support/v7/graphics/package-summary.html', '22.0.0', '', '160');
INSERT INTO `package_list` VALUES ('android.support.v7.graphics.drawable', 'https://developer.android.com/reference/android/support/v7/graphics/drawable/package-summary.html', '23.0.0', '', '161');
INSERT INTO `package_list` VALUES ('android.support.v7.gridlayout', 'https://developer.android.com/reference/android/support/v7/gridlayout/package-summary.html', '', '', '162');
INSERT INTO `package_list` VALUES ('android.support.v7.media', 'https://developer.android.com/reference/android/support/v7/media/package-summary.html', '22.0.0', 'Contains APIs that control the routing of media channels and streams from the current device\n  to external speakers and destination devices.', '163');
INSERT INTO `package_list` VALUES ('android.support.v7.mediarouter', 'https://developer.android.com/reference/android/support/v7/mediarouter/package-summary.html', '', '', '164');
INSERT INTO `package_list` VALUES ('android.support.v7.palette', 'https://developer.android.com/reference/android/support/v7/palette/package-summary.html', '', '', '165');
INSERT INTO `package_list` VALUES ('android.support.v7.preference', 'https://developer.android.com/reference/android/support/v7/preference/package-summary.html', '23.0.0', '', '166');
INSERT INTO `package_list` VALUES ('android.support.v7.recyclerview', 'https://developer.android.com/reference/android/support/v7/recyclerview/package-summary.html', '22.2.0', '', '167');
INSERT INTO `package_list` VALUES ('android.support.v7.util', 'https://developer.android.com/reference/android/support/v7/util/package-summary.html', '22.1.0', '', '168');
INSERT INTO `package_list` VALUES ('android.support.v7.view', 'https://developer.android.com/reference/android/support/v7/view/package-summary.html', '22.0.0', '', '169');
INSERT INTO `package_list` VALUES ('android.support.v7.widget', 'https://developer.android.com/reference/android/support/v7/widget/package-summary.html', '22.0.0', '', '170');
INSERT INTO `package_list` VALUES ('android.support.v7.widget.helper', 'https://developer.android.com/reference/android/support/v7/widget/helper/package-summary.html', '22.2.0', '', '171');
INSERT INTO `package_list` VALUES ('android.support.v7.widget.util', 'https://developer.android.com/reference/android/support/v7/widget/util/package-summary.html', '22.1.0', '', '172');
INSERT INTO `package_list` VALUES ('android.support.v8.renderscript', 'https://developer.android.com/reference/android/support/v8/renderscript/package-summary.html', '23.0.0', '', '173');
INSERT INTO `package_list` VALUES ('android.support.wearable', 'https://developer.android.com/reference/android/support/wearable/package-summary.html', '', '', '174');
INSERT INTO `package_list` VALUES ('android.support.wearable.view', 'https://developer.android.com/reference/android/support/wearable/view/package-summary.html', '26.0.0-alpha1', '', '175');
INSERT INTO `package_list` VALUES ('android.system', 'https://developer.android.com/reference/android/system/package-summary.html', '21', '', '176');
INSERT INTO `package_list` VALUES ('android.telecom', 'https://developer.android.com/reference/android/telecom/package-summary.html', '21', 'The Android Telecom framework is responsible for managing calls on an Android device.', '177');
INSERT INTO `package_list` VALUES ('android.telephony', 'https://developer.android.com/reference/android/telephony/package-summary.html', '1', 'Provides APIs for monitoring the basic phone information, such as\nthe network type and connection state, plus utilities\nfor manipulating phone number strings.', '178');
INSERT INTO `package_list` VALUES ('android.telephony.cdma', 'https://developer.android.com/reference/android/telephony/cdma/package-summary.html', '5', 'Provides APIs for utilizing CDMA-specific telephony features.', '179');
INSERT INTO `package_list` VALUES ('android.telephony.gsm', 'https://developer.android.com/reference/android/telephony/gsm/package-summary.html', '1', 'Provides APIs for utilizing GSM-specific telephony features, such as\ntext/data/PDU SMS messages.', '180');
INSERT INTO `package_list` VALUES ('android.test', 'https://developer.android.com/reference/android/test/package-summary.html', '1', 'A framework for writing Android test cases and suites.', '181');
INSERT INTO `package_list` VALUES ('android.test.mock', 'https://developer.android.com/reference/android/test/mock/package-summary.html', '1', 'Utility classes providing stubs or mocks of various Android framework building blocks.', '182');
INSERT INTO `package_list` VALUES ('android.test.suitebuilder', 'https://developer.android.com/reference/android/test/suitebuilder/package-summary.html', '1', 'Utility classes supporting the test runner classes.', '183');
INSERT INTO `package_list` VALUES ('android.test.suitebuilder.annotation', 'https://developer.android.com/reference/android/test/suitebuilder/annotation/package-summary.html', '1', 'Utility classes supporting the test runner classes.', '184');
INSERT INTO `package_list` VALUES ('android.text', 'https://developer.android.com/reference/android/text/package-summary.html', '1', 'Provides classes used to render or track text and text spans on the screen.', '185');
INSERT INTO `package_list` VALUES ('android.text.format', 'https://developer.android.com/reference/android/text/format/package-summary.html', '3', 'This package contains alternative classes for some text formatting classes\ndefined in ', '186');
INSERT INTO `package_list` VALUES ('android.text.method', 'https://developer.android.com/reference/android/text/method/package-summary.html', '1', 'Provides classes that monitor or modify keypad input.', '187');
INSERT INTO `package_list` VALUES ('android.text.style', 'https://developer.android.com/reference/android/text/style/package-summary.html', '1', 'Provides classes used to view or change the style of a span of text in a View object.', '188');
INSERT INTO `package_list` VALUES ('android.text.util', 'https://developer.android.com/reference/android/text/util/package-summary.html', '1', 'Utilities for converting identifiable text strings into clickable links \nand creating RFC 822-type message (SMTP) tokens.', '189');
INSERT INTO `package_list` VALUES ('android.transition', 'https://developer.android.com/reference/android/transition/package-summary.html', '19', 'The classes in this package enable \"scenes & transitions\" functionality for\nview hiearchies.', '190');
INSERT INTO `package_list` VALUES ('android.util', 'https://developer.android.com/reference/android/util/package-summary.html', '1', 'Provides common utility methods such as date/time manipulation, base64 encoders\nand decoders, string and number conversion methods, and XML utilities.', '191');
INSERT INTO `package_list` VALUES ('android.view', 'https://developer.android.com/reference/android/view/package-summary.html', '1', 'Provides classes that expose basic user interface classes that handle\nscreen layout and interaction with the user.', '192');
INSERT INTO `package_list` VALUES ('android.view.accessibility', 'https://developer.android.com/reference/android/view/accessibility/package-summary.html', '4', '\n  The classes in this package are used to represent screen content and changes to it\n  as well as APIs for querying the global accessibility state of the system.', '193');
INSERT INTO `package_list` VALUES ('android.view.animation', 'https://developer.android.com/reference/android/view/animation/package-summary.html', '1', 'Provides classes that handle tweened animations.', '194');
INSERT INTO `package_list` VALUES ('android.view.autofill', 'https://developer.android.com/reference/android/view/autofill/package-summary.html', 'O', '', '195');
INSERT INTO `package_list` VALUES ('android.view.inputmethod', 'https://developer.android.com/reference/android/view/inputmethod/package-summary.html', '3', 'Framework classes for interaction between views and input methods (such\nas soft keyboards).', '196');
INSERT INTO `package_list` VALUES ('android.view.textclassifier', 'https://developer.android.com/reference/android/view/textclassifier/package-summary.html', 'O', '', '197');
INSERT INTO `package_list` VALUES ('android.view.textservice', 'https://developer.android.com/reference/android/view/textservice/package-summary.html', '14', '', '198');
INSERT INTO `package_list` VALUES ('android.webkit', 'https://developer.android.com/reference/android/webkit/package-summary.html', '1', 'Provides tools for browsing the web.', '199');
INSERT INTO `package_list` VALUES ('android.widget', 'https://developer.android.com/reference/android/widget/package-summary.html', '1', '\nThe widget package contains (mostly visual) UI elements to use\non your Application screen.', '200');
INSERT INTO `package_list` VALUES ('com.android.internal.backup', 'https://developer.android.com/reference/com/android/internal/backup/package-summary.html', '', '', '201');
INSERT INTO `package_list` VALUES ('com.android.internal.inputmethod', 'https://developer.android.com/reference/com/android/internal/inputmethod/package-summary.html', '', '', '202');
INSERT INTO `package_list` VALUES ('com.android.internal.logging', 'https://developer.android.com/reference/com/android/internal/logging/package-summary.html', '', '', '203');
INSERT INTO `package_list` VALUES ('com.android.internal.os', 'https://developer.android.com/reference/com/android/internal/os/package-summary.html', '', '', '204');
INSERT INTO `package_list` VALUES ('com.android.internal.statusbar', 'https://developer.android.com/reference/com/android/internal/statusbar/package-summary.html', '', '', '205');
INSERT INTO `package_list` VALUES ('com.android.internal.widget', 'https://developer.android.com/reference/com/android/internal/widget/package-summary.html', '', '', '206');
INSERT INTO `package_list` VALUES ('com.android.test.runner', 'https://developer.android.com/reference/com/android/test/runner/package-summary.html', '', '', '207');
INSERT INTO `package_list` VALUES ('dalvik.annotation', 'https://developer.android.com/reference/dalvik/annotation/package-summary.html', '1', '', '208');
INSERT INTO `package_list` VALUES ('dalvik.bytecode', 'https://developer.android.com/reference/dalvik/bytecode/package-summary.html', '1', '', '209');
INSERT INTO `package_list` VALUES ('dalvik.system', 'https://developer.android.com/reference/dalvik/system/package-summary.html', '1', '', '210');
INSERT INTO `package_list` VALUES ('java.awt.font', 'https://developer.android.com/reference/java/awt/font/package-summary.html', '1', '', '211');
INSERT INTO `package_list` VALUES ('java.beans', 'https://developer.android.com/reference/java/beans/package-summary.html', '3', '', '212');
INSERT INTO `package_list` VALUES ('java.io', 'https://developer.android.com/reference/java/io/package-summary.html', '1', 'Provides for system input and output through data streams,\nserialization and the file system.', '213');
INSERT INTO `package_list` VALUES ('java.lang', 'https://developer.android.com/reference/java/lang/package-summary.html', '1', 'Provides classes that are fundamental to the design of the Java\n programming language.', '214');
INSERT INTO `package_list` VALUES ('java.lang.annotation', 'https://developer.android.com/reference/java/lang/annotation/package-summary.html', '1', 'Provides library support for the Java programming language\n annotation facility.', '215');
INSERT INTO `package_list` VALUES ('java.lang.invoke', 'https://developer.android.com/reference/java/lang/invoke/package-summary.html', 'O', '', '216');
INSERT INTO `package_list` VALUES ('java.lang.ref', 'https://developer.android.com/reference/java/lang/ref/package-summary.html', '1', 'Provides reference-object classes, which support a limited degree of\n interaction with the garbage collector.', '217');
INSERT INTO `package_list` VALUES ('java.lang.reflect', 'https://developer.android.com/reference/java/lang/reflect/package-summary.html', '1', 'Provides classes and interfaces for obtaining reflective\n information about classes and objects.', '218');
INSERT INTO `package_list` VALUES ('java.math', 'https://developer.android.com/reference/java/math/package-summary.html', '1', '', '219');
INSERT INTO `package_list` VALUES ('java.net', 'https://developer.android.com/reference/java/net/package-summary.html', '1', 'Provides the classes for implementing networking applications.', '220');
INSERT INTO `package_list` VALUES ('java.nio', 'https://developer.android.com/reference/java/nio/package-summary.html', '1', 'Defines buffers, which are containers for data, and provides an overview of the\n other NIO packages.', '221');
INSERT INTO `package_list` VALUES ('java.nio.channels', 'https://developer.android.com/reference/java/nio/channels/package-summary.html', '1', 'Defines channels, which represent connections to entities that are capable of\n performing I/O operations, such as files and sockets; defines selectors, for\n multiplexed, non-blocking I/O operations.', '222');
INSERT INTO `package_list` VALUES ('java.nio.channels.spi', 'https://developer.android.com/reference/java/nio/channels/spi/package-summary.html', '1', 'Service-provider classes for the ', '223');
INSERT INTO `package_list` VALUES ('java.nio.charset', 'https://developer.android.com/reference/java/nio/charset/package-summary.html', '1', 'Defines charsets, decoders, and encoders, for translating between bytes and\n Unicode characters.', '224');
INSERT INTO `package_list` VALUES ('java.nio.charset.spi', 'https://developer.android.com/reference/java/nio/charset/spi/package-summary.html', '1', 'Service-provider classes for the ', '225');
INSERT INTO `package_list` VALUES ('java.nio.file', 'https://developer.android.com/reference/java/nio/file/package-summary.html', 'O', '', '226');
INSERT INTO `package_list` VALUES ('java.nio.file.attribute', 'https://developer.android.com/reference/java/nio/file/attribute/package-summary.html', 'O', '', '227');
INSERT INTO `package_list` VALUES ('java.nio.file.spi', 'https://developer.android.com/reference/java/nio/file/spi/package-summary.html', 'O', '', '228');
INSERT INTO `package_list` VALUES ('java.security', 'https://developer.android.com/reference/java/security/package-summary.html', '1', 'Provides the classes and interfaces for the security framework.', '229');
INSERT INTO `package_list` VALUES ('java.security.acl', 'https://developer.android.com/reference/java/security/acl/package-summary.html', '1', 'The classes and interfaces in this package have been\n superseded by classes in the java.security package.', '230');
INSERT INTO `package_list` VALUES ('java.security.cert', 'https://developer.android.com/reference/java/security/cert/package-summary.html', '1', 'Provides classes and interfaces for parsing and managing\n certificates, certificate revocation lists (CRLs), and\n certification paths.', '231');
INSERT INTO `package_list` VALUES ('java.security.interfaces', 'https://developer.android.com/reference/java/security/interfaces/package-summary.html', '1', 'Provides interfaces for generating RSA (Rivest, Shamir and\n Adleman AsymmetricCipher algorithm)\n keys as defined in the RSA Laboratory Technical Note\n PKCS#1, and DSA (Digital Signature\n Algorithm) keys as defined in NIST\'s FIPS-186.', '232');
INSERT INTO `package_list` VALUES ('java.security.spec', 'https://developer.android.com/reference/java/security/spec/package-summary.html', '1', 'Provides classes and interfaces for key specifications and algorithm\n parameter specifications.', '233');
INSERT INTO `package_list` VALUES ('java.sql', 'https://developer.android.com/reference/java/sql/package-summary.html', '1', 'Provides the API for accessing and processing data stored in a \ndata source (usually a relational database) using the \nJava', '234');
INSERT INTO `package_list` VALUES ('java.text', 'https://developer.android.com/reference/java/text/package-summary.html', '1', 'Provides classes and interfaces for handling text, dates, numbers, and messages\nin a manner independent of natural languages.', '235');
INSERT INTO `package_list` VALUES ('java.time', 'https://developer.android.com/reference/java/time/package-summary.html', 'O', '\n The main API for dates, times, instants, and durations.', '236');
INSERT INTO `package_list` VALUES ('java.time.chrono', 'https://developer.android.com/reference/java/time/chrono/package-summary.html', 'O', '\n Generic API for calendar systems other than the default ISO.', '237');
INSERT INTO `package_list` VALUES ('java.time.format', 'https://developer.android.com/reference/java/time/format/package-summary.html', 'O', '\n Provides classes to print and parse dates and times.', '238');
INSERT INTO `package_list` VALUES ('java.time.temporal', 'https://developer.android.com/reference/java/time/temporal/package-summary.html', 'O', '\n Access to date and time using fields and units, and date time adjusters.', '239');
INSERT INTO `package_list` VALUES ('java.time.zone', 'https://developer.android.com/reference/java/time/zone/package-summary.html', 'O', '\n Support for time-zones and their rules.', '240');
INSERT INTO `package_list` VALUES ('java.util', 'https://developer.android.com/reference/java/util/package-summary.html', '1', 'Contains the collections framework, legacy collection classes, event model,\ndate and time facilities, internationalization, and miscellaneous utility\nclasses (a string tokenizer, a random-number generator, and a bit array).', '241');
INSERT INTO `package_list` VALUES ('java.util.concurrent', 'https://developer.android.com/reference/java/util/concurrent/package-summary.html', '1', 'Utility classes commonly useful in concurrent programming.', '242');
INSERT INTO `package_list` VALUES ('java.util.concurrent.atomic', 'https://developer.android.com/reference/java/util/concurrent/atomic/package-summary.html', '1', 'A small toolkit of classes that support lock-free thread-safe\n programming on single variables.', '243');
INSERT INTO `package_list` VALUES ('java.util.concurrent.locks', 'https://developer.android.com/reference/java/util/concurrent/locks/package-summary.html', '1', 'Interfaces and classes providing a framework for locking and waiting\n for conditions that is distinct from built-in synchronization and\n monitors.', '244');
INSERT INTO `package_list` VALUES ('java.util.function', 'https://developer.android.com/reference/java/util/function/package-summary.html', '24', ' provide target types for lambda expressions\n and method references.', '245');
INSERT INTO `package_list` VALUES ('java.util.jar', 'https://developer.android.com/reference/java/util/jar/package-summary.html', '1', 'Provides classes for reading and writing the JAR (Java ARchive) file\nformat, which is based on the standard ZIP file format with an\noptional manifest file.', '246');
INSERT INTO `package_list` VALUES ('java.util.logging', 'https://developer.android.com/reference/java/util/logging/package-summary.html', '1', '\nProvides the classes and interfaces of \nthe Java', '247');
INSERT INTO `package_list` VALUES ('java.util.prefs', 'https://developer.android.com/reference/java/util/prefs/package-summary.html', '1', 'This package allows applications to store and retrieve user and system\npreference and configuration data.', '248');
INSERT INTO `package_list` VALUES ('java.util.regex', 'https://developer.android.com/reference/java/util/regex/package-summary.html', '1', 'Classes for matching character sequences against patterns specified by regular\nexpressions.', '249');
INSERT INTO `package_list` VALUES ('java.util.stream', 'https://developer.android.com/reference/java/util/stream/package-summary.html', '24', 'Classes to support functional-style operations on streams of elements, such\n as map-reduce transformations on collections.', '250');
INSERT INTO `package_list` VALUES ('java.util.zip', 'https://developer.android.com/reference/java/util/zip/package-summary.html', '1', 'Provides classes for reading and writing the standard ZIP and GZIP\nfile formats.', '251');
INSERT INTO `package_list` VALUES ('javax.crypto', 'https://developer.android.com/reference/javax/crypto/package-summary.html', '1', 'Provides the classes and interfaces for cryptographic operations.', '252');
INSERT INTO `package_list` VALUES ('javax.crypto.interfaces', 'https://developer.android.com/reference/javax/crypto/interfaces/package-summary.html', '1', 'Provides interfaces for Diffie-Hellman keys as defined in\nRSA Laboratories\' PKCS #3.', '253');
INSERT INTO `package_list` VALUES ('javax.crypto.spec', 'https://developer.android.com/reference/javax/crypto/spec/package-summary.html', '1', 'Provides classes and interfaces for key specifications and algorithm\nparameter specifications.', '254');
INSERT INTO `package_list` VALUES ('javax.microedition.khronos.egl', 'https://developer.android.com/reference/javax/microedition/khronos/egl/package-summary.html', '1', '', '255');
INSERT INTO `package_list` VALUES ('javax.microedition.khronos.opengles', 'https://developer.android.com/reference/javax/microedition/khronos/opengles/package-summary.html', '1', 'Provides a standard OpenGL interface.', '256');
INSERT INTO `package_list` VALUES ('javax.net', 'https://developer.android.com/reference/javax/net/package-summary.html', '1', 'Provides classes for networking applications.', '257');
INSERT INTO `package_list` VALUES ('javax.net.ssl', 'https://developer.android.com/reference/javax/net/ssl/package-summary.html', '1', 'Provides classes for the secure socket package.', '258');
INSERT INTO `package_list` VALUES ('javax.security.auth', 'https://developer.android.com/reference/javax/security/auth/package-summary.html', '1', 'This package provides a framework for authentication and\n authorization.', '259');
INSERT INTO `package_list` VALUES ('javax.security.auth.callback', 'https://developer.android.com/reference/javax/security/auth/callback/package-summary.html', '1', 'This package provides the classes necessary for services\n to interact with applications in order to retrieve\n information (authentication data including usernames\n or passwords, for example) or to display information\n (error and warning messages, for example).', '260');
INSERT INTO `package_list` VALUES ('javax.security.auth.login', 'https://developer.android.com/reference/javax/security/auth/login/package-summary.html', '1', 'This package provides a pluggable authentication framework.', '261');
INSERT INTO `package_list` VALUES ('javax.security.auth.x500', 'https://developer.android.com/reference/javax/security/auth/x500/package-summary.html', '1', 'This package contains the classes that should be used to store\n X500 Principal and X500 Private Credentials in a\n ', '262');
INSERT INTO `package_list` VALUES ('javax.security.cert', 'https://developer.android.com/reference/javax/security/cert/package-summary.html', '1', 'Provides classes for public key certificates.', '263');
INSERT INTO `package_list` VALUES ('javax.sql', 'https://developer.android.com/reference/javax/sql/package-summary.html', '1', 'Provides the API for server side data source access and processing from\nthe Java', '264');
INSERT INTO `package_list` VALUES ('javax.xml', 'https://developer.android.com/reference/javax/xml/package-summary.html', '1', '', '265');
INSERT INTO `package_list` VALUES ('javax.xml.datatype', 'https://developer.android.com/reference/javax/xml/datatype/package-summary.html', '8', '', '266');
INSERT INTO `package_list` VALUES ('javax.xml.namespace', 'https://developer.android.com/reference/javax/xml/namespace/package-summary.html', '8', '', '267');
INSERT INTO `package_list` VALUES ('javax.xml.parsers', 'https://developer.android.com/reference/javax/xml/parsers/package-summary.html', '1', '', '268');
INSERT INTO `package_list` VALUES ('javax.xml.transform', 'https://developer.android.com/reference/javax/xml/transform/package-summary.html', '8', '', '269');
INSERT INTO `package_list` VALUES ('javax.xml.transform.dom', 'https://developer.android.com/reference/javax/xml/transform/dom/package-summary.html', '8', '', '270');
INSERT INTO `package_list` VALUES ('javax.xml.transform.sax', 'https://developer.android.com/reference/javax/xml/transform/sax/package-summary.html', '8', '', '271');
INSERT INTO `package_list` VALUES ('javax.xml.transform.stream', 'https://developer.android.com/reference/javax/xml/transform/stream/package-summary.html', '8', '', '272');
INSERT INTO `package_list` VALUES ('javax.xml.validation', 'https://developer.android.com/reference/javax/xml/validation/package-summary.html', '8', '', '273');
INSERT INTO `package_list` VALUES ('javax.xml.xpath', 'https://developer.android.com/reference/javax/xml/xpath/package-summary.html', '8', '', '274');
INSERT INTO `package_list` VALUES ('junit.framework', 'https://developer.android.com/reference/junit/framework/package-summary.html', '1', '', '275');
INSERT INTO `package_list` VALUES ('junit.runner', 'https://developer.android.com/reference/junit/runner/package-summary.html', '1', 'Utility classes supporting the junit test framework.', '276');
INSERT INTO `package_list` VALUES ('org.apache.http.conn', 'https://developer.android.com/reference/org/apache/http/conn/package-summary.html', '1', '', '277');
INSERT INTO `package_list` VALUES ('org.apache.http.conn.scheme', 'https://developer.android.com/reference/org/apache/http/conn/scheme/package-summary.html', '1', '', '278');
INSERT INTO `package_list` VALUES ('org.apache.http.conn.ssl', 'https://developer.android.com/reference/org/apache/http/conn/ssl/package-summary.html', '1', 'TLS/SSL specific parts of the ', '279');
INSERT INTO `package_list` VALUES ('org.apache.http.params', 'https://developer.android.com/reference/org/apache/http/params/package-summary.html', '1', '', '280');
INSERT INTO `package_list` VALUES ('org.json', 'https://developer.android.com/reference/org/json/package-summary.html', '1', '', '281');
INSERT INTO `package_list` VALUES ('org.w3c.dom', 'https://developer.android.com/reference/org/w3c/dom/package-summary.html', '1', '', '282');
INSERT INTO `package_list` VALUES ('org.w3c.dom.ls', 'https://developer.android.com/reference/org/w3c/dom/ls/package-summary.html', '8', '', '283');
INSERT INTO `package_list` VALUES ('org.xml.sax', 'https://developer.android.com/reference/org/xml/sax/package-summary.html', '1', '', '284');
INSERT INTO `package_list` VALUES ('org.xml.sax.ext', 'https://developer.android.com/reference/org/xml/sax/ext/package-summary.html', '1', '', '285');
INSERT INTO `package_list` VALUES ('org.xml.sax.helpers', 'https://developer.android.com/reference/org/xml/sax/helpers/package-summary.html', '1', '', '286');
INSERT INTO `package_list` VALUES ('org.xmlpull.v1', 'https://developer.android.com/reference/org/xmlpull/v1/package-summary.html', '1', '', '287');
INSERT INTO `package_list` VALUES ('org.xmlpull.v1.sax2', 'https://developer.android.com/reference/org/xmlpull/v1/sax2/package-summary.html', '1', '', '288');
